github-actions :: add input validation (#1288)

diff --git a/.github/workflows/cherrypick.yml b/.github/workflows/cherrypick.yml
--- a/.github/workflows/cherrypick.yml
+++ b/.github/workflows/cherrypick.yml
@@ -22,6 +22,9 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Set env
         run: |
@@ -43,6 +46,14 @@ jobs:
         run: |
           echo "No commits specified to cherry pick"
           exit 1
+
+      - name: Check for valid commit(s)
+        if: ${{ env.CHERRYPICK_COMMITS != '' }}
+        run: |
+          if [[ ! "${{ env.CHERRYPICK_COMMITS }}" =~ ^([0-9a-f]{7,40})(\s+[0-9a-f]{7,40})*$ ]]; then
+            echo "Invalid commits to cherry-pick: must contain 7- to 40-character hexadecimal SHA separated by a single space."
+            exit 1
+          fi
 
       - name: Checkout repo
         uses: actions/checkout@v4
diff --git a/.github/workflows/maven-release.yml b/.github/workflows/maven-release.yml
--- a/.github/workflows/maven-release.yml
+++ b/.github/workflows/maven-release.yml
@@ -44,6 +44,15 @@ jobs:
         run: |
           echo "Milestone release is missing a release suffix, i.e. -M1"
           exit 1
+      - name: Check milestone has valid release suffix
+        if: ${{ github.event.inputs.release_type == 'milestone' && github.event.inputs.release_suffix != '' }}
+        run: |
+          if [[ ! "$IN_RELEASE_SUFFIX" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "Invalid release-suffix format: must contain only alphanumeric characters, underscores, dashes, and periods."
+            exit 1
+          fi
+        env:
+          IN_RELEASE_SUFFIX: ${{ github.event.inputs.release_suffix }}
       - name: Check suffix is not specified for a release or patch
         if: ${{ github.event.inputs.release_type != 'milestone' && github.event.inputs.release_suffix != '' }}
         run: |
@@ -58,6 +67,9 @@ jobs:
   get_version:
     needs: verify
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
@@ -75,6 +87,9 @@ jobs:
     permissions:
       contents: write
       packages: write
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Add RELEASE_VERSION to environment variable
         run: echo "RELEASE_VERSION=${{ needs.get_version.outputs.RELEASE_VERSION }}" >> "$GITHUB_ENV"
@@ -146,6 +161,9 @@ jobs:
     permissions:
       contents: write
       pull-requests: write
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
diff --git a/.github/workflows/maven-version.yml b/.github/workflows/maven-version.yml
--- a/.github/workflows/maven-version.yml
+++ b/.github/workflows/maven-version.yml
@@ -18,6 +18,9 @@ env:
 jobs:
   verify:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Check release ends with snapshot
         if: ${{ !endsWith(github.event.inputs.next_version, '-SNAPSHOT') }}
@@ -26,12 +29,23 @@ jobs:
           exit 1
         env:
           IN_NEXT_VERSION: ${{ github.event.inputs.next_version }}
+      - name: Check valid next version
+        run: |
+          if [[ ! "$IN_NEXT_VERSION" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "Invalid next-version format: must contain only alphanumeric characters, underscores, dashes, and periods."
+            exit 1
+          fi
+        env:
+          IN_NEXT_VERSION: ${{ github.event.inputs.next_version }}
   snapshot-bump:
     needs: verify
     runs-on: ubuntu-latest
     permissions:
       contents: write
       pull-requests: write
+    defaults:
+      run:
+        shell: bash
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
